export const OWNER_LOGIN_REQUEST = "OWNER_LOGIN_REQUEST";
export const OWNER_LOGIN_SUCCESS = "OWNER_LOGIN_SUCCESS";
export const OWNER_LOGIN_FAIL = "OWNER_LOGIN_FAIL";

export const OWNER_REGISTER_REQUEST = "OWNER_REGISTER_REQUEST";
export const OWNER_REGISTER_SUCCESS = "OWNER_REGISTER_SUCCESS";
export const OWNER_REGISTER_FAIL = "OWNER_REGISTER_FAIL";

export const OWNER_DETAILS_REQUEST = "OWNER_DETAILS_REQUEST";
export const OWNER_DETAILS_SUCCESS = "OWNER_DETAILS_SUCCESS";
export const OWNER_DETAILS_FAIL = "OWNER_DETAILS_FAIL";


